# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=5000)),
                ('files', models.FileField(blank=True, null=True, upload_to='upload_images/goodtoknow/%Y/%m')),
                ('images', models.ImageField(blank=True, null=True, upload_to='upload_images/goodtoknow/%Y/%m')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
