# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caregories_Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categories_Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=2000)),
                ('ingredient', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='upload_images/pills/%Y/%m/%d')),
                ('category_body', models.ManyToManyField(to='pills.Categories_Body')),
                ('category_gender', models.ManyToManyField(to='pills.Caregories_Gender')),
            ],
        ),
    ]
