# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caregories_Gender',
            new_name='Categories_Gender',
        ),
        migrations.AddField(
            model_name='categories_body',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
