# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0003_auto_20180606_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pills',
            old_name='ingredient',
            new_name='benefit',
        ),
        migrations.AddField(
            model_name='pills',
            name='careful',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pills',
            name='shortage',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pills',
            name='where_it_from',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
