# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 08:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pills', '0004_auto_20180608_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pills.Pills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pills',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='like_user_set', through='pills.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
