# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pills',
            name='english_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
