# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0007_pills_english_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pills',
            name='benefit',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='pills',
            name='careful',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='pills',
            name='description',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='pills',
            name='shortage',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='pills',
            name='where_it_from',
            field=models.TextField(max_length=20000),
        ),
    ]
