# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20180626_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='upload_images/posts/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='upload_images/posts/%Y/%m/%d'),
        ),
    ]
